### PR TITLE
Rewrite dev pipeline to use the new run script to deploy website

### PR DESCRIPTION
**Pull request by Trulsaa**
Depends on #430

### CODE REVIEW

**Comment by TheKnarf** [comment]
Does this depend on #430?

**Review by timorzadir — APPROVED** [review]

**Review by TheKnarf — CHANGES_REQUESTED** [review]
I'm blocking this PR until #430 is merged.

**Comment by TheKnarf** [comment]
If we're going over to Kubernetes then I have two questions:

- Could we at first only change the `dev` pipeline so that we get to test this for a while?
- Could we replace Azure DevOps and only use Github Actions?

**Comment by Trulsaa** [comment]
Only changing the `dev` pipeline is a good idea 👍  Replacing Azure DevOps with Github Actions is not something that is needed now and will only delay this task unnecessarily. But since we are now toing to a bash script it should be easier to do it as a task further down the line.

**Review by TheKnarf — APPROVED** [review]

**Pull request merged**
